version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - "4500"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
    restart: always
